# Generated by Django 4.1.1 on 2022-09-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='pic_cart',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
